### PR TITLE
Translation PT-BR

### PR DESCRIPTION
**Pull request by BryanJuan1**
### Brazilian Portuguese PT-BR
_Hello, how are you ?!
This time, I think it's the correct Pull Request. :)
If you need help with more PT-BR translations, I'll be happy to help._

**Important: For the PT-BR language, code in ANSI so that the accent is correct!**

### CODE REVIEW

**Comment by TheHunterJPScripts** [comment]
Have you tested if the translation shows on the game? I don't know if you can merge 2 languages on the same file. IF you tested it and it works for both languages, y will accept the PR. But i thin that portuguese will need a .._PT.txt and brazilean will need .._BR.txt. I'm not currently on my pc so i can't test it. Let me know if it's ok to merge.

**Comment by BryanJuan1** [comment]
Do you mean for the two languages: Portuguese (PT) and Brazilian Portuguese (PT-BR)? If the two collide in the game? I don't think so, because in the game, there are two different languages for Portuguese, but even so, I'm going to test it here to avoid that. 
And I will answer if there's any trouble. :)

**Comment by BryanJuan1** [comment]
**Hello, I tested the translation in the game, but I have trouble:**
The translation is correct, but when I place the crafting tables, they are so big compared to the player and the other furniture.
- [1 - Translations](https://i.imgur.com/bUhCvLo.png)
- [2 - Crafting Tables](https://i.imgur.com/3STYttU.png)

_Well, the translation is correct, then if you want to accept the PR, it will work fine!
About the crafting tables, I don't know if it's because of the translation or if it was already like that._

**Review by TheHunterJPScripts — APPROVED** [review]
Everything looks fine

**Comment by TheHunterJPScripts** [comment]
The size I think it's related to the 2x textures of the game, some other mods also have this issue that i need to look into it. If you disable double size texture on the game setting it should show them correctly.
I would like to add you on the workshop description as a contributor, how would you like me to refer you (Nickname or name)?

**Comment by BryanJuan1** [comment]
In the workshop can be [☆XIM☆](https://steamcommunity.com/id/BryanXim/). :)
And if you need help with more translations, I'd be glad to help you.
Thx...

**Pull request merged**
